### ISSUE TITLE
Error in build on UE 5.5.4

### ISSUE THREAD

**Issue by HinataAoki** [rive-app/rive-unreal#150]
I faced to build error when I added Rive plugin 0.3.3 and restarted.
I had same error when open `rive-unreal-demos` .

PC: Mac M2
OS: 15.4.1

log are below.
```bash
/Users/Shared/Epic Games/UE_5.5/Engine/Source/Editor/ContentBrowser/Public/ContentBrowserMenuContexts.h:242:112: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
242 |
if (const UContentBrowserAssetContextMenuContext* Context = UContentBrowserAssetContextMenuContext::template
FindContextWithAssets(MenuOrSection))
/Users/Shared/Epic Games/UE_5.5/Engine/Source/Editor/ContentBrowser/Public/ContentBrowserMenuContexts.h:252:112: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
252 |
if (const UContentBrowserAssetContextMenuContext* Context = UContentBrowserAssetContextMenuContext::template
FindContextWithAssets(MenuOrSection))
|
2 errors
```

Any help would be greatly appreciated!
Thanks.

**Comment by xanderseren** [comment]
I am also running into issues getting the build to work on macOS, but i'm getting a different error.

The newest version of the rive unreal plugin works for me on Windows, but does not build on macOS. Using:

Rive Unreal Plugin 0.3.3a-gh
Unreal Engine 5.5.4
macOS Sequoia 15.1 with M1 processor

I’ve tried to make my unreal project a c++ project and build from source as the rive unreal docs suggest. But attempting to build with the rive plugin enabled throws the following error:

```
[38/119] Link [Apple] UnrealEditor-RiveRenderer.dylib (UBA disabled)
Undefined symbols for architecture arm64:
  "Bitmap::RecognizeImageFormat(unsigned char const*, unsigned long)", referenced from:
      RenderContextRHIImpl::platformDecodeImageTexture(rive::Span<unsigned char const>) in RenderContextRHIImpl.cpp.o
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
